var app = new Vue({
    el:"#app",
    data(){
        return {
            count:200,
            modeList:[{
                mode:'normal',
                cn:'正常'
            },{
                mode:'multiply',
                cn:'正片叠底'
            },{
                mode:'screen',
                cn:'滤色'
            },{
                mode:'overlay',
                cn:'叠加'
            },{
                mode:'darken',
                cn:'变暗'
            },{
                mode:'lighten',
                cn:'变亮'
            },{
                mode:'color-dodge',
                cn:'颜色减淡'
            },{
                mode:'color-burn',
                cn:'颜色加深'
            },{
                mode:'hard-light',
                cn:'强光'
            },{
                mode:'soft-light',
                cn:'柔光'
            },{
                mode:'difference',
                cn:'差值'
            },{
                mode:'exclusion',
                cn:'排除'
            },{
                mode:'hue',
                cn:'色相'
            },{
                mode:'saturation',
                cn:'饱和度'
            },{
                mode:'color',
                cn:'颜色'
            },{
                mode:'luminosity',
                cn:'亮度'
            }],
            selectedMode:'normal'
        }
    }
});